### ISSUE TITLE
Docs are failing

### ISSUE THREAD

**Issue by poscat0x04** [oeb25/smtlib-rs#1]
https://docs.rs/crate/smtlib/latest

**Comment by oeb25** [comment]
That's right! I believe the issue is that the `z3-sys` crate with the `static-link-z3` feature takes too long to build, so for now, I think I'll disable that feature for docs.rs.

**Comment by oeb25** [comment]
Just release [v0.1.7](https://docs.rs/smtlib/0.1.7/smtlib/index.html) and [v0.1.6](https://docs.rs/smtlib-lowlevel/0.1.6/smtlib_lowlevel/) so the docs are now back up!
